[theme]
primaryColor="#2E8B57"                  # Main accent color (buttons, sliders)
backgroundColor="#F7F9F9"               # Page background
secondaryBackgroundColor="#FFFFFF"     # Widget background
textColor="#1E1E1E"                    # Text color
font="sans serif"                      # or "serif" / "monospace"
